---
#- name: create cloudera repo
# file: 
#dest: /etc/yum.repos.d/cloudera-manager.repo
# state: touch
- name: add cloudera repo
  yum_repository:
    name: Cloudera Manager 6.1.1
    description: cloudera-manager
    baseurl: https://archive.cloudera.com/cm6/6.1.1/redhat7/yum/
    gpgkey: https://archive.cloudera.com/cm6/6.1.1/redhat7/yum/RPM-GPG-KEY-cloudera
    gpgcheck: 1
    enabled: 1

    #- name: copy repo to /etc/yum.repos.d/
    #  copy:
    #src: files/cloudera.repo
    #  3dest: /etc/yum.repos.d/cloudera-manager.repo
- name: inport GPG keys for cloudera
  command: sudo rpm --import https://archive.cloudera.com/cm6/6.1.0/redhat7/yum/RPM-GPG-KEY-cloudera
